# Generated by Django 5.1.1 on 2024-09-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
